[profile.default]
src = "src"
out = "artifacts"
libs = ["node_modules"]
remappings = [
    "@ensdomains/=node_modules/@ensdomains/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@solidity-parser/=node_modules/solhint/node_modules/@solidity-parser/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "truffle/=node_modules/truffle/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
